/* Automating Stored Procedure through Tasks */
/*
-- The above tables are manually created, which means they are static. If we update the S3 bucket with new data then these 
custom tables will not get updated, again we need to run the code manually to get updated results for new data.
-- So, to overcome this issue, we need to pass all neccessory table creation codes into the Stored Procedures 
and then automate the procedure calling using Tasks as shown below.  */

DROP TABLE ACC_LATEST_TXNS_WITH_BALANCE;
DROP TABLE BANKING_KPI;
DROP TABLE BANK_PROFITABILITY;
DROP TABLE CREDIT_CARD_TXNS;
DROP TABLE LOAN_TXNS;

-- Creating Stored Procedures for our custom tables which are neccessory for our analysis

-- ACC_LATEST_TXNS_WITH_BALANCE
CREATE OR REPLACE PROCEDURE CREATE_OR_REPLACE_ACC_LATEST()
RETURNS STRING
LANGUAGE SQL
AS
$$
CREATE OR REPLACE TABLE ACC_LATEST_TXNS_WITH_BALANCE AS

WITH LATEST_TXN_INFO AS (
SELECT ACCOUNT_ID, YEAR(DATE) AS TXN_YEAR, MONTH(DATE) AS TXN_MONTH, 
MAX(DATE) AS LATEST_TXN_DATE
FROM TRANSACTIONS
GROUP BY 1,2,3
ORDER BY 1,2,3)

SELECT LTI.*, T.BALANCE
FROM TRANSACTIONS AS T
INNER JOIN LATEST_TXN_INFO AS LTI ON T.ACCOUNT_ID = LTI.ACCOUNT_ID AND T.DATE = LTI.LATEST_TXN_DATE
WHERE T.TYPE = 'Credit' -- This assumption is given by client, every month end txn data is 'credit'
ORDER BY T.ACCOUNT_ID, LTI.TXN_YEAR, LTI.TXN_MONTH;
$$;

-- BANKING_KPI
CREATE OR REPLACE PROCEDURE CREATE_OR_REPLACE_BANKING_KPI()
RETURNS STRING
LANGUAGE SQL
AS
$$
CREATE OR REPLACE TABLE BANKING_KPI AS

SELECT ALTB.TXN_YEAR, ALTB.TXN_MONTH, T.BANK, A.ACCOUNT_TYPE,
COUNT(DISTINCT ALTB.ACCOUNT_ID) AS TOT_ACCOUNT,
COUNT(DISTINCT T.TRANS_ID) AS TOT_TXNS,
COUNT(CASE WHEN T.TYPE = 'Credit' THEN 1 END) AS DEPOSIT_COUNT,
COUNT(CASE WHEN T.TYPE = 'Withdrawal' THEN 1 END) AS WITHDRAWAL_COUNT,
SUM(ALTB.BALANCE) AS TOT_BALANCE,
ROUND((DEPOSIT_COUNT/TOT_TXNS)*100, 2) AS DEPOSIT_PERC,
ROUND((WITHDRAWAL_COUNT/TOT_TXNS)*100, 2) AS WITHDRAWAL_PERC,
NVL(TOT_BALANCE/TOT_ACCOUNT, 0) AS AVG_BALANCE, -- if the result is null, NVL will replace that null value with 0.
ROUND(TOT_TXNS/TOT_ACCOUNT, 0) AS TPA -- Transactions per account

FROM TRANSACTIONS AS T
INNER JOIN ACC_LATEST_TXNS_WITH_BALANCE AS ALTB ON T.ACCOUNT_ID = ALTB.ACCOUNT_ID
LEFT OUTER JOIN ACCOUNT AS A ON T.ACCOUNT_ID = A.ACCOUNT_ID
GROUP BY 1,2,3,4
ORDER BY 1,2,3,4;
$$;  

-- BANK_PROFITABILITY
CREATE OR REPLACE PROCEDURE CREATE_OR_REPLACE_BANK_PROFITABILITY()
RETURNS STRING
LANGUAGE SQL
AS
$$
CREATE OR REPLACE TABLE BANK_PROFITABILITY AS 
SELECT TXN_YEAR, BANK,
    CASE 
        WHEN TXN_MONTH >= 4 
            THEN CONCAT(TXN_YEAR, '-', TXN_YEAR + 1) 
        ELSE CONCAT(TXN_YEAR - 1, '-', TXN_YEAR)
    END AS FINANCIAL_YEAR,
    SUM(AVG_BALANCE) AS TOT_AVG_BALANCE_IN_CZK,
    SUM(TOT_BALANCE) AS TOT_BALANCE_IN_CZK, 
    (TOT_AVG_BALANCE_IN_CZK * 0.046735) AS TOT_AVG_BALANCE_IN_USD,
    (TOT_BALANCE_IN_CZK * 0.046735) AS TOT_BALANCE_IN_USD,
    CASE
        WHEN TOT_AVG_BALANCE_IN_USD >= 5000000 THEN 5
        WHEN TOT_AVG_BALANCE_IN_USD >=3000000 AND TOT_AVG_BALANCE_IN_USD < 5000000 THEN 3
        WHEN TOT_AVG_BALANCE_IN_USD >=1000000 AND TOT_AVG_BALANCE_IN_USD < 3000000 THEN 1
        ELSE 0
    END AS INTEREST_RATE_IN_PERC,
    CASE
        WHEN TOT_AVG_BALANCE_IN_USD >= 5000000 THEN (TOT_BALANCE_IN_USD * 0.05)
        WHEN TOT_AVG_BALANCE_IN_USD >=3000000 AND TOT_AVG_BALANCE_IN_USD < 5000000 THEN (TOT_BALANCE_IN_USD * 0.03)
        WHEN TOT_AVG_BALANCE_IN_USD >=1000000 AND TOT_AVG_BALANCE_IN_USD < 3000000 THEN (TOT_BALANCE_IN_USD * 0.01)
        ELSE 0
    END AS PROFIT_EARNED_IN_USD
    
FROM BANKING_KPI
GROUP BY 1,2,3
ORDER BY 1,2;
$$;

-- CREDIT_CARD_TXNS
CREATE OR REPLACE PROCEDURE CREATE_OR_REPLACE_CREDIT_CARD_TXNS()
RETURNS STRING
LANGUAGE SQL
AS
$$
CREATE OR REPLACE TABLE CREDIT_CARD_TXNS AS

WITH CREDIT_CARD_INFO AS (
SELECT A.ACCOUNT_ID, CI.SEX AS GENDER, CI.AGE, A.ACCOUNT_TYPE, C.CARD_ID, C.ISSUED AS CARD_ISSUED_DATE, C.TYPE AS CARD_TYPE
FROM ACCOUNT AS A 
INNER JOIN DISPOSITION AS D ON A.ACCOUNT_ID = D.ACCOUNT_ID
INNER JOIN CARD AS C ON D.DISP_ID = C.DISP_ID 
INNER JOIN CLIENT AS CI ON CI.CLIENT_ID = D.CLIENT_ID)

SELECT T.TRANS_ID, CCI.*, T.bank, YEAR(T.date) AS TXN_YEAR, MONTH(T.DATE) AS TXN_MONTH, T.date AS TXN_DATE, T.amount AS TXN_AMOUNT, T.operation
FROM TRANSACTIONS AS T 
INNER JOIN CREDIT_CARD_INFO AS CCI ON T.ACCOUNT_ID = CCI.ACCOUNT_ID
WHERE OPERATION = 'Credit card withdrawal';
$$;

-- LOAN_TXNS
CREATE OR REPLACE PROCEDURE CREATE_OR_REPLACE_LOAN_TXNS()
RETURNS STRING
LANGUAGE SQL
AS
$$
CREATE OR REPLACE TABLE LOAN_TXNS AS

WITH LOAN_PORTFOLIO AS (
SELECT C.CLIENT_ID, C.SEX, C.AGE, D.DISTRICT_NAME, D.NO_OF_INHABITANTS AS POPULATION, D.REGION,
A.ACCOUNT_ID, A.ACCOUNT_TYPE, L.LOAN_ID, L.DATE AS LOAN_TAKEN_DATE, 
L.AMOUNT AS LOAN_AMOUNT, L.DURATION, L.PAYMENTS AS EMI, L.STATUS
FROM LOAN AS L
INNER JOIN ACCOUNT AS A ON A.ACCOUNT_ID = L.ACCOUNT_ID
INNER JOIN DISTRICT AS D ON A.DISTRICT_ID = D.DISTRICT_CODE
INNER JOIN DISPOSITION AS DIS ON A.ACCOUNT_ID = DIS.ACCOUNT_ID
INNER JOIN CLIENT AS C ON DIS.CLIENT_ID = C.CLIENT_ID
WHERE TYPE = 'OWNER')

SELECT T.TRANS_ID, YEAR(T.DATE) AS TXN_YEAR, MONTH(T.DATE) AS TXN_MONTH, T.DATE AS TXN_DATE, LP.ACCOUNT_ID, LP.ACCOUNT_TYPE, T.TYPE AS TXN_TYPE, T.OPERATION, T.AMOUNT AS TXN_AMOUNT, T.PURPOSE, T.BANK, T.ACCOUNT_PARTERN_ID, LP.LOAN_ID, LP.LOAN_TAKEN_DATE, LP.LOAN_AMOUNT, LP.DURATION, LP.EMI, LP.STATUS, LP.CLIENT_ID, LP.SEX AS GENDER, LP.AGE, LP.DISTRICT_NAME, LP.POPULATION, LP.REGION
FROM LOAN_PORTFOLIO AS LP
LEFT OUTER JOIN TRANSACTIONS AS T ON T.ACCOUNT_ID = LP.ACCOUNT_ID AND T.AMOUNT = LP.EMI;
$$;

SHOW PROCEDURES; 

-- We can call the above procedures manually by running the below codes. 
CALL CREATE_OR_REPLACE_ACC_LATEST();
CALL CREATE_OR_REPLACE_BANKING_KPI();  
CALL CREATE_OR_REPLACE_BANK_PROFITABILITY();
CALL CREATE_OR_REPLACE_CREDIT_CARD_TXNS();
CALL CREATE_OR_REPLACE_LOAN_TXNS();

-- Insted, in order to automate the process we assign these CALL operations to five separate TASKS with different schedule times to avoid overlapping of code execution. 

CREATE OR REPLACE TASK ACC_LATEST_TXNS_WITH_BALANCE
WAREHOUSE = COMPUTE_WH
SCHEDULE =  '1 MINUTE'
AS CALL CREATE_OR_REPLACE_ACC_LATEST();
  
CREATE OR REPLACE TASK BANKING_KPI
WAREHOUSE = COMPUTE_WH
SCHEDULE =  '3 MINUTE'
AS CALL CREATE_OR_REPLACE_BANKING_KPI(); 

CREATE OR REPLACE TASK BANK_PROFITABILITY
WAREHOUSE = COMPUTE_WH
SCHEDULE =  '5 MINUTE'
AS CALL CREATE_OR_REPLACE_BANK_PROFITABILITY();
  
CREATE OR REPLACE TASK CREDIT_CARD_TXNS
WAREHOUSE = COMPUTE_WH
SCHEDULE =  '7 MINUTE'
AS CALL CREATE_OR_REPLACE_CREDIT_CARD_TXNS(); 

CREATE OR REPLACE TASK LOAN_TXNS
WAREHOUSE = COMPUTE_WH
SCHEDULE =  '9 MINUTE'
AS CALL CREATE_OR_REPLACE_LOAN_TXNS(); 

SHOW TASKS;

-- Now we need to RESUME and SUSPEND the tasks according to the cleint data updation behaviour.
 
ALTER TASK ACC_LATEST_TXNS_WITH_BALANCE RESUME;
ALTER TASK BANKING_KPI RESUME;
ALTER TASK BANK_PROFITABILITY RESUME;
ALTER TASK CREDIT_CARD_TXNS RESUME;
ALTER TASK LOAN_TXNS RESUME;

ALTER TASK ACC_LATEST_TXNS_WITH_BALANCE SUSPEND;
ALTER TASK BANKING_KPI SUSPEND; 
ALTER TASK BANK_PROFITABILITY SUSPEND;
ALTER TASK CREDIT_CARD_TXNS SUSPEND; 
ALTER TASK LOAN_TXNS SUSPEND;  


/* 
-- Then whenever we add new data to the S3 bucket's Transaction folder, automatically the new data will be copied into the TRANSACTION table
in Snowflake through Snowpipe. Automatically all the Tasks are gets triggerd and executes the Stored Procedur's code one after the other 
(according to their schedule time). 
-- Then the new data will automatically updated on Power BI report through Scheduled Refresh timings.
Hence the whole process is automated using Stored procedures and Tasks. */